# Configuration file for the Pi unit.
pi_config:
  latitude: 46.33
  longitude: -84.38
  cloud_threshold: 70         
  moon_threshold: 60          
  rain_threshold: 20          
  snow_threshold: 20          
  allow_rain: false           
  allow_snow: false           
  debug: true                 
  timezone: America/Detroit   
  astap_speed: slow           
  astap_search_radius: 180
  astap_fov: 0
  astap_demosaic: true        
  astap_color_correction: true
  num_sample_points: 3        
  exposure_time_us: 5000000   
  astap_speed: slow           
  astap_search_radius: 180
  astap_fov: 0
  astap_demosaic: true        
  astap_color_correction: true
  validation_margin_deg: 1.0

streak_detection:
  min_length: 50
  border_tolerance: 10
  canny_threshold1: 50
  canny_threshold2: 150
  hough_threshold: 50
  max_line_gap: 5
